#!/bin/env python
"""Control which screens are used.

Usage:
    fixdisplays [options]

Options:
    -l, --laptop     enable built-in screen, disable all others.
    -d, --desktop    enable external monitors, disable all others.
    -p, --projector  enable external VGA projector along with built-in screen.
    -s, --swap       swap the displays
    -n, --narrate    narrate the changes
    -q, --quiet      suppress all messages except for error messages
"""

# Imports {{{1
from messenger import Messenger, display, error, fatal, narrate, terminate
from scripts import Sh, ScriptError, sh, script_prefs, join
script_prefs(exit_upon_error = False)
import docopt
import sys

# Constants {{{1
LAPTOP_PREFIX = 'LVDS'
DESKTOP_PREFIX = 'DP'
PROJECTOR_PREFIX = 'VGA'

# use 'pactl list' to determine names of audio sinks                             
# # set to None if it setting the default audio sink is not desired                
EXTERNAL_AUDIO_SINK = 'alsa_output.usb-0d8c_C-Media_USB_Audio_Device-00-Device.analog-stereo'
INTERNAL_AUDIO_SINK = 'alsa_output.pci-0000_00_1b.0.analog-stereo' 

# Configuration class {{{1
class Configuration:
    # __init__() {{{2
    def __init__(self, available_screens, unavailable_screens):
        self.xrandr_cmd = ['xrandr']
        self.available_screens = available_screens

        # configure the screens
        if not self.is_suitable():
            sys.exit('Displays not available to support %s configuration.' % (
                self.__class__.__name__.lower()
            ))

        # disable those screens that are not present
        #for screen in unavailable_screens:
        #    self.disable_screen(screen)

        narrate('Available screens:', ', '.join(available_screens))
        narrate('Unavailable screens:', ', '.join(unavailable_screens))

    # disable_unneeded() {{{2
    def disable_unneeded(self, use):
        for screen in self.available_screens:
            if screen not in use:
                narrate('Disable screen:', screen)
                self.xrandr_cmd += ['--output', screen, '--off']

    # enable_needed() {{{2
    def enable_needed(self, use):
        for screen in use:
            narrate('Enable screen:', screen)
            self.xrandr_cmd += ['--output', screen, '--auto']

    # primary_screen() {{{2
    def primary_screen(self, screen):
        narrate('Primary screen:', screen)
        self.xrandr_cmd += ['--output', screen, '--primary']

    # arrange_screens() {{{2
    def arrange_screens(self, screens):
        if len(screens) == 2:
            if cmdline['--swap']:
                right, left = screens
            else:
                left, right = screens
            narrate('Arrange screens:', ', '.join([left, right]))
            self.xrandr_cmd += ['--output', left, '--right-of', right]
        else:
            assert len(screens) <= 2
            assert len(screens) >= 1

    # run_xrandr() {{{2
    def run_xrandr(self):
        try:
            narrate('RUNNING:', ' '.join(self.xrandr_cmd))
            Sh(self.xrandr_cmd)
        except ScriptError as exception:
            error('Could not configure screen with xrandr: %s' % exception)

    # set_default_sound_sink() {{{2
    def set_default_sound_sink(self, sink):
        try:
            narrate('Set default sound sink: %s' % sink)
            Sh('pactl set-default-sink %s' % sink)
        except ScriptError:
            error('Could not set default sound sink: %s' % sink)

# define known configurations
# known configuration -- laptop without projector {{{1
class Laptop(Configuration):
    @classmethod
    def is_suitable(cls):
        return bool(laptop_screens)

    def configure(self):
        use = laptop_screens[0:1]
        display('Configuring laptop screen:', ', '.join(use))
        self.disable_unneeded(use)
        self.enable_needed(use)
        self.primary_screen(use[0])
        self.run_xrandr()
        self.set_default_sound_sink(INTERNAL_AUDIO_SINK)

# known configuration -- home desk {{{1
class Desktop(Configuration):
    @classmethod
    def is_suitable(cls):
        return bool(desktop_screens)

    def configure(self):
        use = desktop_screens[0:2]
        display('Configuring desktop screens:', ', '.join(use))
        self.disable_unneeded(use)
        self.enable_needed(use)
        self.primary_screen(use[0])
        self.arrange_screens(use)
        self.run_xrandr()
        self.set_default_sound_sink(EXTERNAL_AUDIO_SINK)

# known configuration -- laptop with projector {{{1
class Projector(Configuration):
    @classmethod
    def is_suitable(cls):
        return bool(projectors)

    def configure(self):
        use = [laptop_screens[0], projectors[0]]
        display('Configuring laptop screen with projector:', ', '.join(use))
        self.disable_unneeded(use)
        self.enable_needed(use)
        self.primary_screen(laptop_screens[0])
        self.arrange_screens(use)
        self.run_xrandr()
        self.set_default_sound_sink(INTERNAL_AUDIO_SINK)

# unknown configuration -- just turn on all available screens {{{1
class Available(Configuration):
    @classmethod
    def is_suitable(cls):
        return bool(available_screens)

    def configure(self):
        display(
            'Unknown configuration, enabling all available screens:',
            ', '.join(self.available_screens)
        )
        # enable those screens that are present
        self.enable_screen(self.available_screens)
        self.run_xrandr()
        sys.exit()

# Main {{{1
def reset_keyboard():
    sh('r')

try:
    cmdline = docopt.docopt(__doc__)
    Messenger(
        quiet=cmdline['--quiet'],
        narrate=cmdline['--narrate'],
        logfile = join('~/.fixdisplays.log')
    )
    reset_keyboard()

    # determine which screens are present and which are not
    xrandr = Sh(['xrandr', '--query'], modes='OeW')
    available_screens = set()
    unavailable_screens = set()
    for line in xrandr.stdout.split('\n'):
        words = line.split()
        if len(words) >= 2:
            if words[1] == 'connected':
                available_screens.add(words[0])
            elif words[1] == 'disconnected':
                unavailable_screens.add(words[0])

    laptop_screens = []
    desktop_screens = []
    projectors = []
    for screen in sorted(available_screens):
        if screen.startswith(LAPTOP_PREFIX):
            laptop_screens.append(screen)
        elif screen.startswith(DESKTOP_PREFIX):
            desktop_screens.append(screen)
        elif screen.startswith(PROJECTOR_PREFIX):
            projectors.append(screen)
        else:
            errro('%s: unknown screen type' % screen)

    # identify configuration and activate it
    if cmdline['--laptop']:
        configuration = Laptop(available_screens, unavailable_screens)
    elif cmdline['--desktop']:
        configuration = Desktop(available_screens, unavailable_screens)
    elif cmdline['--projector']:
        configuration = Projector(available_screens, unavailable_screens)
    elif Desktop.is_suitable():
        configuration = Desktop(available_screens, unavailable_screens)
    elif Projector.is_suitable():
        configuration = Projector(available_screens, unavailable_screens)
    elif Laptop.is_suitable():
        configuration = Laptop(available_screens, unavailable_screens)
    else:
        configuration = Available(available_screens, unavailable_screens)
    configuration.configure()

except ScriptError as exception:
    fatal(exception)
except KeyboardInterrupt:
    display('Killed by user.')
terminate()
